# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mChat

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'GTMSessionFetcher'
pod 'lottie-ios'
pod 'SkyFloatingLabelTextField'
pod 'IGColorPicker'
pod 'Mapbox-iOS-SDK'

end
