# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mChat

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'lottie-ios'
pod 'LTHRadioButton'
pod 'Mapbox-iOS-SDK', '~> 5.6’


end
